# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
public class operations
{ 
  public static void main(String[] args)
   {
     int n1=50,n2=10;
     System.out.println("Addition");
     int sum=n1+n2;
     System.out.println("sum of n1 and n2="+sum);
     System.out.println("Subtraction");
     int subt=n1-n2;
     System.out.println("Difference between n1 and n2="+subt);
     System.out.println("Multiplication");
     int multiply=n1*n2;
     System.out.println("Product of n1 and n2="+multiply);
     System.out.println("Division");
     int div=n1/n2;
     System.out.println("Quotient of n1 and n2="+div);
     }
}

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test
